# codecov.yml (repo root)
fixes:
  - "v2/::"
  - "*/work/*/*/::"
  - "*/runner/*/work/*/*/::"
ignore:
  - "tests/**"
  - "venv/**"

coverage:
  status:
    project:
      default:
        target: 0.90
        threshold: 0.01
    patch:
      default:
        target: 0.90
        threshold: 0.01
